columns:
- id: yPv
  name: Notes
list:
- color: red
  enabled: true
  params:
  - k: yPv
    v: Swagger-UI
  rules:
  - - content: '"swagger":'
      dataSource: response
      field: body
      method: iContains
  - - content: '"swaggerVersion":'
      dataSource: response
      field: body
      method: iContains
  - - content: Swagger UI
      dataSource: response
      field: title
      method: contains
- color: red
  enabled: true
  params:
  - k: yPv
    v: OpenAPI
  rules:
  - - content: 'Content-Type: application/json'
      dataSource: response
      field: header
      method: contains
    - content: '"openapi":'
      dataSource: response
      field: body
      method: contains
- color: green
  enabled: true
  params:
  - k: yPv
    v: UEditor
  rules:
  - - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: ueditor.*?\.js
      dataSource: response
      field: header
      method: regex
  - - content: javascript
      dataSource: response
      field: header
      method: contains
    - content: UEditor
      dataSource: response
      field: body
      method: contains
  - - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: /ueditor/php/
      dataSource: response
      field: body
      method: iContains
- color: green
  enabled: true
  params:
  - k: yPv
    v: Shiro
  rules:
  - - content: rememberMe=
      dataSource: response
      field: header
      method: iContains
  - - content: =deleteMe
      dataSource: response
      field: header
      method: iContains
- color: gray
  enabled: true
  params:
  - k: yPv
    v: Springboot
  rules:
  - - content: 0488faca4c19046b94d07c3ee83cf9d6
      dataSource: response
      field: bodyMd5
      method: equals
    - content: '200'
      dataSource: response
      field: status
      method: equals
  - - content: '116323821'
      dataSource: response
      field: bodyHash
      method: equals
    - content: '200'
      dataSource: response
      field: status
      method: equals
  - - content: Whitelabel Error Page
      dataSource: response
      field: body
      method: iContains
    - content: '200'
      dataSource: response
      field: status
      method: equals
- color: gray
  enabled: true
  params:
  - k: yPv
    v: Tomcat
  rules:
  - - content: Tomcat
      dataSource: response
      field: server
      method: iContains
  - - content: Apache-Coyote
      dataSource: response
      field: server
      method: iContains
  - - content: Apache Tomcat
      dataSource: response
      field: body
      method: iContains
  - - content: '-297069493'
      dataSource: response
      field: bodyHash
      method: equals
- color: gray
  enabled: true
  params:
  - k: yPv
    v: Struts2
  rules:
  - - content: .do
      dataSource: request
      field: url
      method: contains
  - - content: .action
      dataSource: request
      field: url
      method: contains
- color: green
  enabled: false
  params:
  - k: yPv
    v: JSON Web Token
  rules:
  - - content: (eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9._-]{10,}|eyJ[A-Za-z0-9_\/+-]{10,}\.[A-Za-z0-9._\/+-]{10,})
      dataSource: response
      field: body
      method: regex
- color: yellow
  enabled: true
  params:
  - k: yPv
    v: Java Deserialization
  rules:
  - - content: javax.faces.ViewState
      dataSource: response
      field: body
      method: contains
- color: yellow
  enabled: false
  params:
  - k: yPv
    v: Upload Form
  rules:
  - - content: type="file"
      dataSource: response
      field: body
      method: iContains
- color: orange
  enabled: true
  params:
  - k: yPv
    v: Druid
  rules:
  - - content: Druid Stat Index
      dataSource: response
      field: body
      method: iContains
  - - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: com.alibaba.druid
      dataSource: response
      field: body
      method: iContains
    - content: DbType
      dataSource: response
      field: body
      method: iContains
    - content: DriverClassName
      dataSource: response
      field: body
      method: iContains
    - content: 'jdbc:'
      dataSource: response
      field: body
      method: iContains
  - - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: Content
      dataSource: response
      field: body
      method: iContains
    - content: Version
      dataSource: response
      field: body
      method: iContains
    - content: Drivers
      dataSource: response
      field: body
      method: iContains
    - content: com.alibaba.druid.
      dataSource: response
      field: body
      method: iContains
    - content: JavaVMName
      dataSource: response
      field: body
      method: iContains
    - content: JavaVersion
      dataSource: response
      field: body
      method: iContains
    - content: JavaClassPath
      dataSource: response
      field: body
      method: iContains
    - content: StartTime
      dataSource: response
      field: body
      method: iContains
- color: green
  enabled: true
  params:
  - k: yPv
    v: PDF.js Viewer
  rules:
  - - content: pdf.worker
      dataSource: response
      field: body
      method: iContains
- color: red
  enabled: true
  params:
  - k: yPv
    v: Vite DevMode
  rules:
  - - content: /@vite/client
      dataSource: response
      field: body
      method: contains
- color: cyan
  enabled: true
  params:
  - k: yPv
    v: Debug Logic Parameters
  rules:
  - - content: ((access=)|(adm=)|(admin=)|(alter=)|(cfg=)|(clone=)|(config=)|(create=)|(dbg=)|(debug=)|(delete=)|(disable=)|(edit=)|(enable=)|(exec=)|(execute=)|(grant=)|(load=)|(make=)|(modify=)|(rename=)|(reset=)|(root=)|(shell=)|(test=)|(toggl=))
      dataSource: request
      field: data
      method: iRegex
- color: red
  enabled: true
  params:
  - k: yPv
    v: Passwd File
  rules:
  - - content: /root:/bin/bash
      dataSource: response
      field: body
      method: contains
- color: red
  enabled: true
  params:
  - k: yPv
    v: Win.ini File
  rules:
  - - content: for 16-bit app
      dataSource: response
      field: body
      method: contains
- color: yellow
  enabled: true
  params:
  - k: yPv
    v: pprof-debug
  rules:
  - - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: ((heap profile:)|(Alloc))
      dataSource: response
      field: data
      method: iRegex
    - content: (text/plain)
      dataSource: response
      field: header
      method: iRegex
  - - content: '((Types of profiles available:)|(Profile Descriptions)|(goroutine
        profile: total))'
      dataSource: response
      field: data
      method: iRegex
    - content: '200'
      dataSource: response
      field: status
      method: equals
- color: yellow
  enabled: true
  params:
  - k: yPv
    v: node-exporter-metrics
  rules:
  - - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: ((node_cooling_device)|(node_network))
      dataSource: response
      field: data
      method: iRegex
- color: pink
  enabled: true
  params:
  - k: yPv
    v: kubelet-metrics
  rules:
  - - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: ((<title>kube metrics server</title>)|(kube_configmap_)|(kube_pod_)|(kube_secret_)|(kube_deployment_)|(kube_namespace_)|(kube_service_))
      dataSource: response
      field: data
      method: iRegex
- color: red
  enabled: true
  params:
  - k: yPv
    v: Springboot-heapdump
  rules:
  - - content: 1f8b080000000000
      dataSource: response
      field: bodyHex
      method: iContains
  - - content: 4a4156412050524f46494c45
      dataSource: response
      field: bodyHex
      method: iRegex
  - - content: 4850524f46
      dataSource: response
      field: bodyHex
      method: iRegex
- color: gray
  enabled: true
  params:
  - k: yPv
    v: debug-vars
  rules:
  - - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: (("memstats":)|("cmdline":))
      dataSource: response
      field: data
      method: iRegex
- color: gray
  enabled: true
  params:
  - k: yPv
    v: prometheus-metrics
  rules:
  - - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: ^(?!.*(?:lvm_|kube|namedprocess|mysqld|collectd_|libvirt_|mongodb|blackbox_|haproxy_|rabbitmq_)).*(?:cpu_seconds_total|http_request_duration_seconds|process_virtual_memory_bytes|process_start_time_seconds)
      dataSource: response
      field: data
      method: iRegex
- color: yellow
  enabled: true
  params:
  - k: yPv
    v: Springboot-actuator
  rules:
  - - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: (("_links":)|("self":))
      dataSource: response
      field: data
      method: iRegex
    - content: ((application/json)|(application/vnd.spring-boot.actuator)|(.spring-boot.actuator.))
      dataSource: response
      field: header
      method: iRegex
- color: yellow
  enabled: true
  params:
  - k: yPv
    v: Springboot-env
  rules:
  - - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: ((server.port)|(local.server.port))
      dataSource: response
      field: body
      method: iRegex
    - content: ((application/json)|(application/vnd.spring-boot.actuator))
      dataSource: response
      field: header
      method: iRegex
    - content: ((applicationConfig)|(activeProfiles))
      dataSource: response
      field: body
      method: iRegex
- color: yellow
  enabled: false
  params:
  - k: yPv
    v: Springboot-httptrace
  rules:
  - - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: (("timestamp":)|("traces":)|("method":))
      dataSource: response
      field: body
      method: iRegex
    - content: ((application/json)|(application/vnd.spring-boot.actuator))
      dataSource: response
      field: header
      method: iRegex
- color: gray
  enabled: true
  params:
  - k: yPv
    v: binary
  rules:
  - - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: ((7573746172003030)|(7573746172202000))
      dataSource: response
      field: bodyHex
      method: iRegex
    - content: application/[-\w.]+
      dataSource: response
      field: header
      method: regex
  - - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: (377ABCAF271C)
      dataSource: response
      field: bodyHex
      method: iRegex
    - content: application/[-\w.]+
      dataSource: response
      field: header
      method: regex
  - - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: (314159265359)
      dataSource: response
      field: bodyHex
      method: iRegex
    - content: application/[-\w.]+
      dataSource: response
      field: header
      method: regex
  - - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: (53514c69746520666f726d6174203300)
      dataSource: response
      field: bodyHex
      method: iRegex
    - content: application/[-\w.]+
      dataSource: response
      field: header
      method: regex
  - - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: (1f8b)
      dataSource: response
      field: bodyHex
      method: iRegex
    - content: application/[-\w.]+
      dataSource: response
      field: header
      method: regex
  - - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: ((526172211A0700)|(526172211A070100))
      dataSource: response
      field: bodyHex
      method: iRegex
    - content: application/[-\w.]+
      dataSource: response
      field: header
      method: regex
  - - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: (FD377A585A0000)
      dataSource: response
      field: bodyHex
      method: iRegex
    - content: application/[-\w.]+
      dataSource: response
      field: header
      method: regex
  - - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: ((1F9D)|(1FA0))
      dataSource: response
      field: bodyHex
      method: iRegex
    - content: application/[-\w.]+
      dataSource: response
      field: header
      method: regex
  - - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: (4C5A4950)
      dataSource: response
      field: bodyHex
      method: iRegex
    - content: application/[-\w.]+
      dataSource: response
      field: header
      method: regex
  - - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: (504B0304)
      dataSource: response
      field: bodyHex
      method: iRegex
    - content: application/[-\w.]+
      dataSource: response
      field: header
      method: regex
  - - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: (000100005374616E64617264204A657420444200)
      dataSource: response
      field: bodyHex
      method: iRegex
    - content: application/x-msaccess
      dataSource: response
      field: header
      method: regex
  - - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: (54415045)
      dataSource: response
      field: bodyHex
      method: iRegex
  - - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: (D0CF11E0A1B11AE1)
      dataSource: response
      field: bodyHex
      method: iRegex
  - - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: (000100005374616E64617264204A657420444200)
      dataSource: response
      field: bodyHex
      method: iRegex
    - content: application/x-msaccess
      dataSource: response
      field: header
      method: regex
- color: yellow
  enabled: true
  params:
  - k: yPv
    v: OSS-ListBucket
  rules:
  - - content: ((xml)|(version)|(encoding)|(ListBucketResult)|(Name)|(Prefix)|(Marker)|(MaxKeys)|(Delimiter)|(IsTruncated)|(Contents)|(Key)|(LastModified)|(ETag)|(Type)|(Size)|(StorageClass)|(Owner)|(ID)|(DisplayName))
      dataSource: response
      field: body
      method: iRegex
    - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: application/xml
      dataSource: response
      field: header
      method: contains
- color: magenta
  enabled: true
  params:
  - k: yPv
    v: wsdl
  rules:
  - - content: text/html
      dataSource: response
      field: header
      method: contains
    - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: Available SOAP services
      dataSource: response
      field: body
      method: contains
    - content: -//W3C//DTD
      dataSource: response
      field: body
      method: contains
    - content: Endpoint address
      dataSource: response
      field: body
      method: contains
- color: orange
  enabled: true
  params:
  - k: yPv
    v: Chinese IDCard
  rules:
  - - content: '[^0-9]((\d{8}(0\d|10|11|12)([0-2]\d|30|31)\d{3}$)|(\d{6}(18|19|20)\d{2}(0[1-9]|10|11|12)([0-2]\d|30|31)\d{3}(\d|X|x)))[^0-9]'
      dataSource: response
      field: body
      method: regex
- color: red
  enabled: true
  params:
  - k: yPv
    v: swagger-api
  rules:
  - - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: (?i)(?:swagger:|Swagger 2\\.0|\"swagger\":|Swagger UI|loadSwaggerUI|id=\"swagger-ui)
      dataSource: response
      field: body
      method: iRegex
- color: yellow
  enabled: true
  params:
  - k: yPv
    v: JDBC Connection
  rules:
  - - content: (jdbc:[a-z]+[0-9]?:\/\/[a-z0-9.\-_:;=/@?,&]+)
      dataSource: response
      field: body
      method: iRegex
- color: yellow
  enabled: true
  params:
  - k: yPv
    v: Springboot-nacosconfig
  rules:
  - - content: (("NacosConfigProperties":)|("serverAddr":)|("username":)|("password":))
      dataSource: response
      field: body
      method: iRegex
    - content: '200'
      dataSource: response
      field: status
      method: equals
    - content: ((application/json)|(application/vnd.spring-boot.actuator))
      dataSource: response
      field: header
      method: iRegex
